CREATE TABLE Notes (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    UserId NVARCHAR(450) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Note NVARCHAR(MAX) NOT NULL,
    CONSTRAINT FK_Notes_AspNetUsers FOREIGN KEY (UserId) REFERENCES auth.AspNetUsers(Id) ON DELETE CASCADE
);
