
CREATE TABLE Patient ( 
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	UserId NVARCHAR(450) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	BirthDate NVARCHAR (100) NOT NULL,
	City NVARCHAR (100) NOT NULL,
	Hospital NVARCHAR (200) NOT NULL,
	CONSTRAINT FK_Patient_AspNetUsers FOREIGN KEY (UserId)
	REFERENCES auth.AspNetUsers(Id) ON DELETE CASCADE
);